#ifndef INC_STM32F446XX_NVIC_H_
#define INC_STM32F446XX_NVIC_H_

typedef enum{
	IRQ_WWDG,
	IRQ_PVD,
	IRQ_TAMP_STAMP,
	IRQ_RTC_WKUP,
	IRQ_FLASH,
	IRQ_RCC,
	IRQ_EXTI0,
	IRQ_EXTI1,
	IRQ_EXTI2,
	IRQ_EXTI3,
	IRQ_EXTI4,
	IRQ_DMA1_STREAM0,
	IRQ_DMA1_STREAM1,
	IRQ_DMA1_STREAM2,
	IRQ_DMA1_STREAM3,
	IRQ_DMA1_STREAM4,
	IRQ_DMA1_STREAM5,
	IRQ_DMA1_STREAM6,
	IRQ_ADC,
	IRQ_CAN1_TX,
	IRQ_CAN1_RX0,
	IRQ_CAN1_RX1,
	IRQ_CAN1_SCE,
	IRQ_EXTI9_5,
	IRQ_TIM1_BRK_TIM9,
	IRQ_TIM1_UP_TIM10,
	IRQ_TIM1_TRG_COM_TIM11,
	IRQ_TIM1_CC,
	IRQ_TIM2,
	IRQ_TIM3,
	IRQ_TIM4,
	IRQ_12C1_EV,
	IRQ_I2C1_ER,
	IRQ_I2C2_EV,
	IRQ_I2C2_ER,
	IRQ_SPI1,
	IRQ_SPI2,
	IRQ_USART1,
	IRQ_USART2,
	IRQ_USART3,
	IRQ_EXTI15_10,
	IRQ_RTC_ALARM,
	IRQ_OTG_FS_WKUP,
	IRQ_TIM8_BRK_TIM12,
	IRQ_TIM8_UP_TIM13,
	IRQ_TIM8_TRG_COM_TIM14,
	IRQ_TIM_CC,
	IRQ_DMA1_STREAM7,
	IRQ_FMC,
	IRQ_SDIO,
	IRQ_TIM5,
	IRQ_SPI3,
	IRQ_UART4,
	IRQ_UART5,
	IRQ_TIM6_DAC,
	IRQ_TIM7,
	IRQ_DMA2_STREAM0,
	IRQ_DMA2_STREAM1,
	IRQ_DMA2_STREAM2,
	IRQ_DMA2_STREAM3,
	IRQ_DMA2_STREAM4,
	IRQ_CAN2_TX = 63,
	IRQ_CAN2_RX0,
	IRQ_CAN2_RX1,
	IRQ_CAN2_SCE,
	IRQ_OTG_FS,
	IRQ_DMA2_STREAM5,
	IRQ_DMA2_STREAM6,
	IRQ_DMA2_STREAM7,
	IRQ_USART6,
	IRQ_I2C3_EV,
	IRQ_I2C3_ER,
	IRQ_OTG_HS_EP1_OUT,
	IRQ_OTG_HS_EP1_IN,
	IRQ_OTG_HS_WKUP,
	IRQ_OTG_HS,
	IRQ_DCMI,
	IRQ_FPU = 81,
	IRQ_SPI4 = 84,
	IRQ_SAI1 = 87,
	IRQ_SAI2 = 91,
	IRQ_QUADSPI,
	IRQ_HDMI_CEC,
	IRQ_SPDIF_RX,
	IRQ_FMPI2C1_EV,
	IRQ_FMPI2C1_ER
} IRQ_t;

void NVIC_enable_IRQ(IRQ_t IRQ);

void NVIC_disable_IRQ(IRQ_t IRQ);

void NVIC_set_pending_IRQ(IRQ_t IRQ);

void NVIC_clear_pending_IRQ(IRQ_t IRQ);

void NVIC_set_priority_IRQ(IRQ_t IRQ, uint8_t priority);

uint32_t NVIC_get_pending_IRQ(IRQ_t IRQ);

uint32_t NVIC_get_priority_IRQ(IRQ_t IRQ);

#endif
